### ISSUE TITLE
P2P Discovery of Portals on Network via REST

### ISSUE THREAD

**Issue by pcfreak30** [SkynetLabs/skynet-webportal#2153]
* Enable `/skynet/portals` to be the result of "gossiping" portals on the sia p2p network. This can be cached and may include detection of register-only portals.
* Use this in the kernel for detection of portals with `progressiveFetch`, and possibly store in localStorage the list.

The result will enable the discovery of all portals based on access to a single portal node in the same way DHT effectively works.

**Comment by DavidVorick** [comment]
We want portal ops  to have control over which portals get listed so that there is some level of quality control. It's not really a decentralized way to discover portals as a user either (trusting the output of a single endpoint).

For user discovery, the intention is that users will scan their friends portals, and that they will crawl through all the portals listed by other operators.

p2p discovery of portals is also not really a concern until there are enough portals that you can't just sticky the list to a discord channel.

**Comment by pcfreak30** [comment]
I understand. `It's not really a decentralized way to discover portals as a user either (trusting the output of a single endpoint).` to me, this is moot with the base sector API.

**Comment by MSevey** [comment]
closing for now as this won't be worked on for the foreseeable future. 
once we are at the point of 10s of portals, we can revisit this topic
