### ISSUE TITLE
File detected as virus when downloading directory with ?format=zip

### ISSUE THREAD

**Issue by DaWe35** [SkynetLabs/skynet-webportal#521]
Chrome & Firefox does not allow me to download files that are HNS domains. Example: https://sky-id.hns.siasky.net?format=zip

**Comment by kwypchlo** [comment]
Thanks @DaWe35 I will be reviewing that issue.

**Comment by kwypchlo** [comment]
Cleaning up some old issues 👋  I suspect the problem was due to browsers marking downloads from siasky.net as dangerous and potentially containing harmful content. I just checked and it's not the case any more. We've added a malware scanner and abuse prevention measures to improve our domain's reputation. Downloading from portals on different domains should work just fine.
